name: Push to Central Repository

on:
  push:
    branches:
      - dev

jobs:
  sync-to-central-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup SSH Keys
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Setup Git User
        run: |
          git config --global user.name "Bartoszkk"
          git config --global user.email "Bartosz.michalak@epitech.eu"

      - name: Sync to Central Repository
        env:
          CENTRAL_REPO: 'git@github.com:EpitechPromo2026/B-DEV-500-TLS-5-2-area-alexandre.lagasse.git'
        run: |
          # Adding central repository
          rsync -av --exclude='.git' --exclude='.github' --exclude='AREA-WEB' ./ ../AREA-WEBCP/
          git remote add central "${CENTRAL_REPO}"
          git fetch central
          
          git checkout -b local-main central/main
          
          if [ -d "AREA-WEB/" ]; then
            git rm -rf AREA-WEB/
            mkdir AREA-WEB
            git add AREA-WEB
            git commit -m "Remove existing AREA-WEB directory"
          else
            mkdir AREA-WEB
          fi


          rsync -av --exclude='.git' --exclude='.github' --exclude='AREA-WEB' ../AREA-WEBCP/. AREA-WEB/

          # Commit and push the changes
          git add AREA-WEB
          git commit -m "Update AREA-WEB content"
          git push central local-main:main