name: Build and push Docker images

on:
  push:
    branches:
      - dev
      - test

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: bartoszkk/web:latest

    - name: Notify Azure to pull the latest image
      run: |
        curl -X POST ${{ secrets.AZURE_LINK }} -H "Content-Length: 0"

